- name: bug
  color: d73a4a
  description: Something is not working
- name: enhancement
  color: a2eeef
  description: New feature or request
- name: documentation
  color: 0075ca
  description: Improvements or additions to documentation
- name: question
  color: d876e3
  description: Further information is requested
- name: task
  color: fbca04
  description: General task or chore
- name: area: app
  color: 1d76db
- name: area: docs
  color: 1d76db
- name: area: android
  color: 1d76db
- name: area: ios
  color: 1d76db
- name: area: web
  color: 1d76db
- name: area: assets
  color: 1d76db
